version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: booth-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: boothpassword123
      MONGO_INITDB_DATABASE: booth_registrations
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - booth-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booth-nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:boothpassword123@mongodb:27017/booth_registrations?authSource=admin
      NEXTAUTH_SECRET: your-secret-key-change-this-in-production
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - booth-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public

networks:
  booth-network:
    driver: bridge

volumes:
  mongodb_data: